#!/usr/bin/env bash

echo ---------------------------------------------------------------
echo
echo Hello Human
echo Let''s get your electron app dependencies ready to go
echo
echo ---------------------------------------------------------------
echo
echo Installing app dependencies...
echo

npm install

echo
echo ---------------------------------------------------------------
echo
echo Done!
